"""Descripción del cambio

Revision ID: 0fb28279e0dd
Revises: 2b9168c665e2
Create Date: 2026-08-13 05:58:18.567434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb28279e0dd'
down_revision: Union[str, Sequence[str], None] = '2b9168c665e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'data_available_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('packages', 'data_available_end',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'data_available_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('packages', 'data_available_start',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
