"""fix_celebration_autoincrement

Revision ID: 12dcc570dd69
Revises: f1f2cf740446
Create Date: 2026-08-10 04:58:05.918654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12dcc570dd69'
down_revision: Union[str, Sequence[str], None] = 'f1f2cf740446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
