"""fix_autoincrement_images_and_catalog

Revision ID: 2a955cdfa479
Revises: a4c57a479726
Create Date: 2026-08-09 23:35:48.558590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a955cdfa479'
down_revision: Union[str, Sequence[str], None] = 'a4c57a479726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
