"""Add new column to packages

Revision ID: 2b9168c665e2
Revises: 1bd407bd0914
Create Date: 2026-08-11 03:21:03.443363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9168c665e2'
down_revision: Union[str, Sequence[str], None] = '1bd407bd0914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('data_available_start', sa.Date(), nullable=True))
    op.add_column('packages', sa.Column('data_available_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'data_available_end')
    op.drop_column('packages', 'data_available_start')
    # ### end Alembic commands ###
