"""fix_package_model_and_relations

Revision ID: 2c638acd61e2
Revises: 95aed8ee32c2
Create Date: 2026-08-14 05:58:35.668990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c638acd61e2'
down_revision: Union[str, Sequence[str], None] = '95aed8ee32c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Renombrar columnas si existen con nombre antiguo
    # (opcional: si ya tenías data_available_start/end)
    op.alter_column('packages', 'data_available_start', new_column_name='date_available_start')
    op.alter_column('packages', 'data_available_end', new_column_name='date_available_end')
    # Si no existen, las crea con nullable=True
    # 2. Agregar celebration_id (si no existe)
    op.add_column('packages', sa.Column('celebration_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_packages_celebration', 'packages', 'celebrations', ['celebration_id'], ['id'])
    # 3. Hacer que celebration_id sea NOT NULL (si ya tienes datos, primero rellenar con algún valor)
    # op.alter_column('packages', 'celebration_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'celebration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('packages', 'data_available_end',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('packages', 'data_available_start',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    # ### end Alembic commands ###
