"""Make catalog fks nullable

Revision ID: 4b6681fa6a85
Revises: 01ef7c455663
Create Date: 2026-08-09 21:25:03.122069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6681fa6a85'
down_revision: Union[str, Sequence[str], None] = '01ef7c455663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images_catalog', 'package_id', nullable=True)
    op.alter_column('images_catalog', 'space_id', nullable=True)
    op.alter_column('images_catalog', 'banner_id', nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images_catalog', 'package_id', nullable=False)
    op.alter_column('images_catalog', 'space_id', nullable=False)
    op.alter_column('images_catalog', 'banner_id', nullable=False)
    pass
    # ### end Alembic commands ###
