"""fix_celebrations_autoincrement

Revision ID: 556832dbeaf8
Revises: 12dcc570dd69
Create Date: 2026-08-10 05:25:07.803161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556832dbeaf8'
down_revision: Union[str, Sequence[str], None] = '12dcc570dd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
