"""add_celebration_id_and_date_fields_to_packages

Revision ID: 95aed8ee32c2
Revises: 8960d0ed2d5b
Create Date: 2026-08-14 05:26:55.422538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95aed8ee32c2'
down_revision: Union[str, Sequence[str], None] = '8960d0ed2d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Añadir celebration_id (nullable por ahora, luego podrías hacerlo NOT NULL después de poblarlo)
    op.add_column('packages', sa.Column('celebration_id', sa.Integer(), nullable=True))
    # Si quieres que las fechas sean NOT NULL, asegúrate de que existan datos o establece un valor por defecto
    # Por ejemplo, podrías poner una fecha por defecto:
    op.alter_column('packages', 'data_available_start', nullable=False, server_default=sa.func.current_date())
    op.alter_column('packages', 'data_available_end', nullable=False, server_default=sa.func.current_date())
    # Luego crear la FK
    op.create_foreign_key('packages_celebration_id_fkey', 'packages', 'celebrations', ['celebration_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.alter_column('packages', 'data_available_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('packages', 'data_available_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('packages', 'celebration_id')
    # ### end Alembic commands ###
