"""create_table_gallery_category_and_gallery_image

Revision ID: b45115376df5
Revises: e604c3db38d6
Create Date: 2026-08-16 21:20:09.026545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45115376df5'
down_revision: Union[str, Sequence[str], None] = 'e604c3db38d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'celebration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'celebration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
